"""initial

Revision ID: 8c35eaab34b3
Revises:
Create Date: 2026-06-13 17:04:55.288905

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c35eaab34b3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drinks",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__drinks")),
        sa.UniqueConstraint("title", name=op.f("uq__drinks__title")),
    )
    op.create_table(
        "invitations",
        sa.Column("is_plan_visit", sa.Boolean(), nullable=False),
        sa.Column("music", sa.String(length=255), nullable=True),
        sa.Column("comment", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__invitations")),
    )
    op.create_table(
        "guests",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("invitation_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["invitations.id"],
            name=op.f("fk__guests__invitation_id__invitations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__guests")),
    )
    op.create_table(
        "invitations_to_drinks",
        sa.Column("invitation_id", sa.Integer(), nullable=False),
        sa.Column("drink_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["drink_id"], ["drinks.id"], name=op.f("fk__invitations_to_drinks__drink_id__drinks")
        ),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["invitations.id"],
            name=op.f("fk__invitations_to_drinks__invitation_id__invitations"),
        ),
        sa.PrimaryKeyConstraint(
            "invitation_id", "drink_id", name=op.f("pk__invitations_to_drinks")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invitations_to_drinks")
    op.drop_table("guests")
    op.drop_table("invitations")
    op.drop_table("drinks")
    # ### end Alembic commands ###
