import type { Metadata } from "next";
import "./globals.css";
import type { PropsWithChildren } from "react";
import { Footer } from "@/shared/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
